// Study materials as HTTP: the slide renders and the written explanation that
// the reading screen shows. They live on disk next to the other blobs, NOT in
// the sync snapshot — 55 MB of slide images would blow its 32 MB budget, and
// the material is the same for every device anyway.
//
// Kdo co vidí — tři vrstvy, a záleží na tom, protože v appce jsou i cizí lidé:
//   /data/materials/            Danielovy vlastní učebnice. VIDÍ JE JEN ADMIN.
//   /data/materials/demo/       jedna ukázková učebnice, tu vidí každý.
//   /data/materials/users/<id>/ co si kdo nahrál sám (viz pub.js).
//
// Rejstříků je víc (`index-<předmět>.json`) a server je slévá do jednoho
// seznamu kurzů. Jeden společný `index.json` by znamenal, že druhý předmět
// přepíše první.
import { createReadStream, existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { DATA_DIR } from './store.js'
import { userMaterialsDir } from './pub.js'

const MATERIALS_DIR = join(DATA_DIR, 'materials')
const DEMO_DIR = join(MATERIALS_DIR, 'demo')

// Ids and file names are generated by the pipeline, never by a user. Anything
// that does not match exactly is refused before it can touch the filesystem.
// Vlastní učebnice nesou před ID přednášky šestiznakový prefix balíčku, proto
// je strop 24 a ne 12.
const LECTURE_RE = /^[A-Za-z0-9]{2,24}$/
// Balíčky karet vedle učebnice: deck-<id>.json. Bez nich by se karty musely
// hledat jako soubor na disku a ručně vkládat do okna Import.
const DECK_RE = /^[a-z0-9][a-z0-9-]{0,40}$/
const IMAGE_RE = /^[A-Za-z0-9]{2,24}_s\d{3}\.webp$/
const INDEX_RE = /^index-[a-z0-9-]{1,41}\.json$/

function readJsonFile(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    return null
  }
}

/**
 * Adresáře, ze kterých ten který uživatel smí číst, v pořadí přednosti.
 * Vlastní nahrané učebnice první: když si někdo nahraje balíček stejného
 * jména, platí ten jeho — dal si ho tam sám.
 */
function readableDirs(user) {
  const dirs = []
  const own = userMaterialsDir(user?.id)
  if (own) dirs.push(own)
  if (existsSync(DEMO_DIR)) dirs.push(DEMO_DIR)
  // Kořen je Danielova soukromá knihovna. Ostatní k ní nemají co čichat —
  // je to jeho studijní materiál, ne obsah appky.
  if (user?.isAdmin) dirs.push(MATERIALS_DIR)
  return dirs
}

function indexFilesIn(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((f) => (dir === MATERIALS_DIR && f === 'index.json') || INDEX_RE.test(f))
    .sort()
    .map((f) => join(dir, f))
}

/**
 * Jeden rejstřík ze všech předmětů, které uživatel smí vidět. Kurzy se spojí
 * za sebe; kdyby se stejný kód kurzu objevil dvakrát, platí ten, který se
 * načte první — tedy ten z bližšího adresáře.
 */
function mergedIndex(user) {
  const courses = []
  const seen = new Set()
  // Témata zkoušky ze všech předmětů za sebou. Klíč nese číslo kurzu, takže
  // se „téma 1" z jednoho předmětu nepotká s „tématem 1" z druhého.
  const topics = []
  const topicKeys = new Set()
  let exam = null
  for (const dir of readableDirs(user)) {
    for (const file of indexFilesIn(dir)) {
      const part = readJsonFile(file)
      if (!part || !Array.isArray(part.courses)) continue
      exam ??= part.exam ?? null
      for (const topic of part.topics ?? []) {
        if (!topic?.key || topicKeys.has(topic.key)) continue
        topicKeys.add(topic.key)
        topics.push(topic)
      }
      for (const course of part.courses) {
        if (!course?.code || seen.has(course.code)) continue
        seen.add(course.code)
        courses.push(course)
      }
    }
  }
  return courses.length ? { exam, topics, courses } : null
}

export function materialsAvailable(user) {
  return mergedIndex(user) !== null
}

/** Balíčky karet v jednom adresáři, jen jejich popis (ne karty). */
function decksIn(dir, own) {
  if (!existsSync(dir)) return []
  const out = []
  for (const file of readdirSync(dir).sort()) {
    const m = /^deck-([a-z0-9][a-z0-9-]{0,40})\.json$/.exec(file)
    if (!m) continue
    const deck = readJsonFile(join(dir, file))
    if (!deck || typeof deck.subject !== 'string') continue
    out.push({
      id: m[1],
      subject: deck.subject,
      examDate: deck.examDate ?? null,
      cards: Array.isArray(deck.cards) ? deck.cards.length : 0,
      filing: Array.isArray(deck.filing) ? deck.filing.length : 0,
      own,
    })
  }
  return out
}

function deckList(user) {
  const out = []
  const ids = new Set()
  const ownDir = userMaterialsDir(user?.id)
  for (const dir of readableDirs(user)) {
    for (const deck of decksIn(dir, dir === ownDir)) {
      if (ids.has(deck.id)) continue
      ids.add(deck.id)
      out.push(deck)
    }
  }
  return out
}

/**
 * Najde soubor učebnice v adresáři, na který uživatel dosáhne, a vrátí i ten
 * adresář — obrázky se hledají vedle něj, takže se tím zároveň ohlídá, že
 * cizí slidy nepůjdou stáhnout jen proto, že někdo uhodl jméno souboru.
 */
function resolveMaterial(user, name) {
  for (const dir of readableDirs(user)) {
    const path = join(dir, name)
    if (existsSync(path)) return { dir, path }
  }
  return null
}

export function registerMaterialRoutes(app, { requireUser }) {
  app.get('/api/materials', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const index = mergedIndex(user)
    if (!index) return reply.code(404).send({ error: 'no materials' })
    // The index is small and changes only on upload; a short cache keeps the
    // screen instant on back-navigation without hiding a fresh upload for long.
    reply.header('cache-control', 'private, max-age=60')
    return index
  })

  // Co je ke stažení. Karty samotné až na vyžádání — seznam má být malý.
  app.get('/api/materials/decks', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    reply.header('cache-control', 'private, max-age=60')
    return { decks: deckList(user) }
  })

  app.get('/api/materials/deck/:id', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { id } = req.params
    if (!DECK_RE.test(id)) return reply.code(400).send({ error: 'bad id' })
    const found = resolveMaterial(user, `deck-${id}.json`)
    const deck = found ? readJsonFile(found.path) : null
    if (!deck) return reply.code(404).send({ error: 'unknown deck' })
    reply.header('cache-control', 'private, max-age=60')
    return deck
  })

  app.get('/api/materials/lecture/:id', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { id } = req.params
    if (!LECTURE_RE.test(id)) return reply.code(400).send({ error: 'bad id' })
    const found = resolveMaterial(user, `${id}.json`)
    const lecture = found ? readJsonFile(found.path) : null
    if (!lecture) return reply.code(404).send({ error: 'unknown lecture' })
    reply.header('cache-control', 'private, max-age=300')
    return lecture
  })

  app.get('/api/materials/img/:lecture/:file', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { lecture, file } = req.params
    if (!LECTURE_RE.test(lecture) || !IMAGE_RE.test(file)) {
      return reply.code(400).send({ error: 'bad path' })
    }
    // Obrázek se vydá jen tomu, kdo smí i samotnou přednášku — a jen z toho
    // adresáře, ve kterém ta přednáška leží.
    const found = resolveMaterial(user, `${lecture}.json`)
    if (!found) return reply.code(404).send({ error: 'not found' })
    const path = join(found.dir, 'img', lecture, file)
    if (!existsSync(path)) return reply.code(404).send({ error: 'not found' })
    // A slide render never changes under the same name — the pipeline writes a
    // new name when a deck changes — so it can be cached for a year.
    reply.header('cache-control', 'private, max-age=31536000, immutable')
    reply.header('content-length', String(statSync(path).size))
    reply.type('image/webp')
    return reply.send(createReadStream(path))
  })
}
