// Study materials as HTTP: the slide renders and the written explanation that
// the reading screen shows. They live on disk next to the other blobs, NOT in
// the sync snapshot — 55 MB of slide images would blow its 32 MB budget, and
// the material is the same for every device anyway.
//
// Layout:  /data/materials/{index-<předmět>.json,<LECTURE>.json,img/<LECTURE>/<file>.webp}
//
// Předmětů je víc a každý nahrává svůj rejstřík zvlášť (`index-irewi.json`,
// `index-pravni-dejiny.json`); server je slévá do jednoho seznamu kurzů. Jeden
// společný `index.json` by znamenal, že druhý předmět přepíše první.
import { createReadStream, existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { DATA_DIR } from './store.js'

const MATERIALS_DIR = join(DATA_DIR, 'materials')

// Ids and file names are generated by the pipeline, never by a user. Anything
// that does not match exactly is refused before it can touch the filesystem.
const LECTURE_RE = /^[A-Za-z0-9]{2,12}$/
// Balíčky karet vedle učebnice: deck-<id>.json. Bez nich by se karty musely
// hledat jako soubor na disku a ručně vkládat do okna Import.
const DECK_RE = /^[a-z0-9][a-z0-9-]{0,40}$/
const IMAGE_RE = /^[A-Za-z0-9]{2,12}_s\d{3}\.webp$/

function readJsonFile(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    return null
  }
}

/** Rejstříky na disku: `index-<předmět>.json` plus starší jednotný `index.json`. */
function indexFiles() {
  if (!existsSync(MATERIALS_DIR)) return []
  return readdirSync(MATERIALS_DIR)
    .filter((f) => f === 'index.json' || /^index-[a-z0-9-]{1,40}\.json$/.test(f))
    .sort()
}

/**
 * Jeden rejstřík ze všech předmětů. Kurzy se spojí za sebe; kdyby se stejný kód
 * kurzu objevil dvakrát (typicky starý `index.json` vedle nového
 * `index-irewi.json`), platí ten, který se načte první.
 */
function mergedIndex() {
  const courses = []
  const seen = new Set()
  let exam = null
  for (const file of indexFiles()) {
    const part = readJsonFile(join(MATERIALS_DIR, file))
    if (!part || !Array.isArray(part.courses)) continue
    exam ??= part.exam ?? null
    for (const course of part.courses) {
      if (!course?.code || seen.has(course.code)) continue
      seen.add(course.code)
      courses.push(course)
    }
  }
  return courses.length ? { exam, courses } : null
}

export function materialsAvailable() {
  return mergedIndex() !== null
}

/** Balíčky karet ležící v /data/materials, jen jejich popis (ne karty). */
function deckList() {
  if (!existsSync(MATERIALS_DIR)) return []
  const out = []
  for (const file of readdirSync(MATERIALS_DIR).sort()) {
    const m = /^deck-([a-z0-9][a-z0-9-]{0,40})\.json$/.exec(file)
    if (!m) continue
    const deck = readJsonFile(join(MATERIALS_DIR, file))
    if (!deck || typeof deck.subject !== 'string') continue
    out.push({
      id: m[1],
      subject: deck.subject,
      examDate: deck.examDate ?? null,
      cards: Array.isArray(deck.cards) ? deck.cards.length : 0,
      filing: Array.isArray(deck.filing) ? deck.filing.length : 0,
    })
  }
  return out
}

export function registerMaterialRoutes(app, { requireUser }) {
  app.get('/api/materials', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const index = mergedIndex()
    if (!index) return reply.code(404).send({ error: 'no materials' })
    // The index is small and changes only on upload; a short cache keeps the
    // screen instant on back-navigation without hiding a fresh upload for long.
    reply.header('cache-control', 'private, max-age=60')
    return index
  })

  // Co je ke stažení. Karty samotné až na vyžádání — seznam má být malý.
  app.get('/api/materials/decks', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    reply.header('cache-control', 'private, max-age=60')
    return { decks: deckList() }
  })

  app.get('/api/materials/deck/:id', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { id } = req.params
    if (!DECK_RE.test(id)) return reply.code(400).send({ error: 'bad id' })
    const deck = readJsonFile(join(MATERIALS_DIR, `deck-${id}.json`))
    if (!deck) return reply.code(404).send({ error: 'unknown deck' })
    reply.header('cache-control', 'private, max-age=60')
    return deck
  })

  app.get('/api/materials/lecture/:id', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { id } = req.params
    if (!LECTURE_RE.test(id)) return reply.code(400).send({ error: 'bad id' })
    const lecture = readJsonFile(join(MATERIALS_DIR, `${id}.json`))
    if (!lecture) return reply.code(404).send({ error: 'unknown lecture' })
    reply.header('cache-control', 'private, max-age=300')
    return lecture
  })

  app.get('/api/materials/img/:lecture/:file', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { lecture, file } = req.params
    if (!LECTURE_RE.test(lecture) || !IMAGE_RE.test(file)) {
      return reply.code(400).send({ error: 'bad path' })
    }
    const path = join(MATERIALS_DIR, 'img', lecture, file)
    if (!existsSync(path)) return reply.code(404).send({ error: 'not found' })
    // A slide render never changes under the same name — the pipeline writes a
    // new name when a deck changes — so it can be cached for a year.
    reply.header('cache-control', 'private, max-age=31536000, immutable')
    reply.header('content-length', String(statSync(path).size))
    reply.type('image/webp')
    return reply.send(createReadStream(path))
  })
}
