// Study materials as HTTP: the slide renders and the written explanation that
// the reading screen shows. They live on disk next to the other blobs, NOT in
// the sync snapshot — 55 MB of slide images would blow its 32 MB budget, and
// the material is the same for every device anyway.
//
// Layout:  /data/materials/{index.json,<LECTURE>.json,img/<LECTURE>/<file>.webp}
import { createReadStream, existsSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { DATA_DIR } from './store.js'

const MATERIALS_DIR = join(DATA_DIR, 'materials')

// Ids and file names are generated by the pipeline, never by a user. Anything
// that does not match exactly is refused before it can touch the filesystem.
const LECTURE_RE = /^[A-Za-z0-9]{2,12}$/
const IMAGE_RE = /^[A-Za-z0-9]{2,12}_s\d{3}\.webp$/

function readJsonFile(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    return null
  }
}

export function materialsAvailable() {
  return existsSync(join(MATERIALS_DIR, 'index.json'))
}

export function registerMaterialRoutes(app, { requireUser }) {
  app.get('/api/materials', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const index = readJsonFile(join(MATERIALS_DIR, 'index.json'))
    if (!index) return reply.code(404).send({ error: 'no materials' })
    // The index is small and changes only on upload; a short cache keeps the
    // screen instant on back-navigation without hiding a fresh upload for long.
    reply.header('cache-control', 'private, max-age=60')
    return index
  })

  app.get('/api/materials/lecture/:id', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { id } = req.params
    if (!LECTURE_RE.test(id)) return reply.code(400).send({ error: 'bad id' })
    const lecture = readJsonFile(join(MATERIALS_DIR, `${id}.json`))
    if (!lecture) return reply.code(404).send({ error: 'unknown lecture' })
    reply.header('cache-control', 'private, max-age=300')
    return lecture
  })

  app.get('/api/materials/img/:lecture/:file', async (req, reply) => {
    const user = requireUser(req, reply)
    if (!user) return
    const { lecture, file } = req.params
    if (!LECTURE_RE.test(lecture) || !IMAGE_RE.test(file)) {
      return reply.code(400).send({ error: 'bad path' })
    }
    const path = join(MATERIALS_DIR, 'img', lecture, file)
    if (!existsSync(path)) return reply.code(404).send({ error: 'not found' })
    // A slide render never changes under the same name — the pipeline writes a
    // new name when a deck changes — so it can be cached for a year.
    reply.header('cache-control', 'private, max-age=31536000, immutable')
    reply.header('content-length', String(statSync(path).size))
    reply.type('image/webp')
    return reply.send(createReadStream(path))
  })
}
